name: grocery_brasil_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.8.1
  firebase_core: "^0.5.0"
  firebase_auth: "^0.18.0+1"
  flutter_facebook_auth: ^0.2.3
  google_sign_in: ^4.5.1
  provider: ^4.3.2+1
  webview_flutter: ^0.3.22+1
  cloud_firestore: ^0.14.0+2
  intl: ^0.16.1
  barcode_scan: ^3.0.1
  qr_flutter: ^3.1.0
  flutter_typeahead: ^1.8.8
  geolocator: ^6.0.0
  flutter_native_admob: ^2.1.0+3
  flutter_bloc: ^6.1.0
  bloc: ^6.1.0
  equatable: ^1.2.5
  dartz: ^0.9.1
  sprintf: ^5.0.0
  get_it: ^5.0.1
  dart_geohash: ^1.0.2

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - images/groceries.svg
